routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Contacts
Route::delete('/contacts/delete-multiple', 'ContactController@destroyMultiple')->name('contacts.delete-multiple');
Route::post('/contacts/import', 'ContactController@import')->name('contacts.import');
Route::resource('contacts', 'ContactController');


//Groups
Route::delete('/groups/delete-multiple', 'GroupController@destroyMultiple')->name('groups.delete-multiple');
Route::post('/groups/add-contacts', 'GroupController@addContacts')->name('groups.add-contacts');
Route::resource('groups', 'GroupController');
Route::get('/groups/{group}/contacts', 'GroupController@getContacts')->name('groups.get-contacts');

// Campaigns
Route::resource('campaigns', 'CampaignController');

//mails
Route::get('email', 'CampaignController@store');

Route::resource('support', 'SupportController');

resources/views/partials/aside.blade.php
<!-- begin:: Aside -->
<button class="kt-aside-close " id="kt_aside_close_btn"><i class="la la-close"></i></button>
<div class="kt-aside  kt-aside--fixed  kt-grid__item kt-grid kt-grid--desktop kt-grid--hor-desktop" id="kt_aside">

    <!-- begin:: Aside -->
    <div class="kt-aside__brand kt-grid__item  " id="kt_aside_brand">
        <div class="kt-aside__brand-logo">
            <a href="{{ route('contacts.index') }}">
                <img alt="Logo" src="{{ asset('assets/media/logos/weband2.png') }}" />
            </a>
        </div>
    </div>

    <!-- end:: Aside -->

    <!-- begin:: Aside Menu -->
    <div class="kt-aside-menu-wrapper kt-grid__item kt-grid__item--fluid" id="kt_aside_menu_wrapper">
        <div id="kt_aside_menu" class="kt-aside-menu  kt-aside-menu--dropdown " data-ktmenu-vertical="1" data-ktmenu-dropdown="1" data-ktmenu-scroll="0">
            <ul class="kt-menu__nav ">
                <li class="kt-menu__item{{ Request::segment(1) == 'contacts' ? ' kt-menu__item--here' : '' }}" aria-haspopup="true"><a href="{{ route('contacts.index') }}" class="kt-menu__link"><i class="kt-menu__link-icon flaticon-user"></i><span class="kt-menu__link-text">Контакти</span></a></li>
                <li class="kt-menu__item{{ Request::segment(1) == 'groups' ? ' kt-menu__item--here' : '' }}" aria-haspopup="true"><a href="{{ route('groups.index') }}" class="kt-menu__link "><i class="kt-menu__link-icon flaticon2-group"></i><span class="kt-menu__link-text">Групи</span></a></li>
                <li class="kt-menu__item{{ Request::segment(1) == 'campaigns' ? ' kt-menu__item--here' : '' }}" aria-haspopup="true"><a href="{{ route('campaigns.index') }}" class="kt-menu__link "><i class="kt-menu__link-icon flaticon2-mail-1"></i><span class="kt-menu__link-text">Кампании</span></a></li>
            </ul>
        </div>
    </div>

    <!-- end:: Aside Menu -->
</div>

<!-- end:: Aside -->

resources/views/partials/wysiwyg-script.blade.php
<!-- WYSIWYG -->
<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
<script>
    tinymce.init({
        // Warning: the selector must match with the id attribute
        selector: 'textarea.wysiwyg',
        height: 300,
        plugins: [
            'advlist autolink lists link charmap print preview anchor',
            'searchreplace visualblocks code fullscreen',
            'insertdatetime media table contextmenu paste code',
            'textcolor'
        ],
        toolbar: 'undo redo | insert | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | forecolor backcolor | fontsizeselect fontselect',
        content_css: '//www.tinymce.com/css/codepen.min.css',
        relative_urls : false,
        remove_script_host : false,
        convert_urls : true,
    });
</script>
<link rel="stylesheet" type="text/css" href="http://cdn.tinymce.com/4/skins/lightgray/skin.min.css">