routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Contacts
Route::delete('/contacts/delete-multiple', 'ContactController@destroyMultiple')->name('contacts.delete-multiple');
Route::post('/contacts/import', 'ContactController@import')->name('contacts.import');
Route::resource('contacts', 'ContactController');


//Groups
Route::delete('/groups/delete-multiple', 'GroupController@destroyMultiple')->name('groups.delete-multiple');
Route::post('/groups/add-contacts', 'GroupController@addContacts')->name('groups.add-contacts');
Route::resource('groups', 'GroupController');
Route::get('/groups/{group}/contacts', 'GroupController@getContacts')->name('groups.get-contacts');

// Campaigns
Route::resource('campaigns', 'CampaignController');

//mails
Route::get('email', 'CampaignController@store');

Route::resource('support', 'SupportController');

app/Contact.php
<?php

namespace App;
use Illuminate\Database\Eloquent\SoftDeletes;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    use SoftDeletes;

    protected $fillable = ['user_id', 'first_name', 'last_name', 'email'];

    // public function newCollection(array $models = [])
    // {
    //     return new ContactCollection($models);
    // }

    public function user()
    {
        return $this->belongsTo('App\User')->withDefault([
            'name' => '-'
        ]);
    }

    public function groups()
    {
        return $this->belongsToMany('App\Group');
    }

    public function fullname()
    {
        return "{$this->first_name} {$this->last_name}";
    }
}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use App\Contact;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Imports\ContactsImport;
use Maatwebsite\Excel\Facades\Excel;

class ContactController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $contacts = Auth::user()->contacts;
        $groups = Auth::user()->groups;

        return view('contacts.index', compact("contacts", "groups"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('contacts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $contact = new Contact();
        $contact->user()->associate(Auth::user());
        $contact->first_name = $request->first_name;
        $contact->last_name = $request->last_name;
        $contact->email = $request->email;
        $contact->save();

        return redirect()->route('contacts.index')->with('success', 'Contact added!');
    }

    public function import(Request $request)
    {
        Excel::import(new ContactsImport, $request->file);

        return redirect()->back()->witch('success', 'Contact imported!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function show(Contact $contact)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function edit(Contact $contact)
    {
        return view('contacts.edit', compact("contact"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Contact $contact)
    {
        $contact->first_name = $request->first_name;
        $contact->last_name = $request->last_name;
        $contact->email = $request->email;
        $contact->save();

        return redirect()->route('contacts.index')->with('success', 'Contact updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, Contact $contact)
    {
        if ($contact->delete()) {
            if ($request->ajax()) {
                return response()->json([
                    'success' => true,
                    'message' => 'The contact was deleted'
                ]);
            }

            return redirect()->back()->with('success', 'The contact was deleted');
        }

        if ($request->ajax()) {
            return response()->json()([
                'success' => false,
                'message' => 'There was a problem deleting the contact'
            ]);
        }

        return redirect()->back()->with('error', 'There was a problem deleting the contact');
    }

    public function destroyMultiple(Request $request)
    {
        $contacts = Contact::whereIn('id', $request->contacts)->get();

        if (Contact::whereIn('id', $request->contacts)->delete()) {
            if ($request->ajax()) {
                return response()->json([
                    'success' => true,
                    'message' => 'The contacts were deleted'
                ]);
            }

            return redirect()->back()->with('success', 'The contacts were deleted');
        }

        if ($request->ajax()) {
            return response()->json([
                'success' => false,
                'message' => 'There was a problem deleting the contacts'
            ]);
        }

        return redirect()->back()->with('error', 'There was a problem deleting the contacts');
    }
}

resources/views/contacts/create.blade.php
@extends('layouts.master')

@section('title', 'Създай контакт')
@section('page-title', 'Създай контакт')

@section('content')
    <div class="row">
        <div class="col-md-6">

            <!--begin::Portlet-->
            <div class="kt-portlet">
                <div class="kt-portlet__head">
                    <div class="kt-portlet__head-label">
                        <h3 class="kt-portlet__head-title">
                            Информация за контакта
                        </h3>
                    </div>
                </div>

                <!--begin::Form-->
                <form class="kt-form" method="POST" action="{{ route('contacts.store') }}">
                    @csrf

                    <div class="kt-portlet__body">
                        @if($errors->any())
                            <div class="form-group form-group-last">
                                <div class="alert alert-danger" role="alert">
                                    <div class="alert-icon"><i class="flaticon-warning kt-font-white"></i></div>
                                    <div class="alert-text">
                                        Вънзикнаха грешки
                                    </div>
                                </div>
                            </div>
                        @endif
                        <div class="form-group">
                            <label for="first_name">Име</label>
                            <input type="text" class="form-control" name="first_name" id="first_name" value="{{ old('first_name') }}">
                            @error('first_name') <span class="form-text text-danger">{{ $message }}</span> @enderror
                        </div>
                        <div class="form-group">
                            <label for="last_name">Фамилия</label>
                            <input type="text" class="form-control" name="last_name" id="last_name" value="{{ old('last_name') }}">
                            @error('last_name') <span class="form-text text-danger">{{ $message }}</span> @enderror
                        </div>
                        <div class="form-group">
                            <label for="email">Имейл адрес</label>
                            <input type="email" class="form-control" name="email" id="email" value="{{ old('email') }}">
                            @error('email') <span class="form-text text-danger">{{ $message }}</span> @enderror
                        </div>
                    </div>
                    <div class="kt-portlet__foot">
                        <div class="kt-form__actions text-right">
                            <button type="submit" class="btn btn-primary">Създай</button>
                        </div>
                    </div>
                </form>

                <!--end::Form-->
            </div>

            <!--end::Portlet-->

        </div>
    </div>
@endsection

resources/views/contacts/edit.blade.php
@extends('layouts.master')

@section('title', 'Редактирай контакт')
@section('page-title', 'Редактирай контакт')

@section('content')
    <div class="row">
        <div class="col-md-6">

            <!--begin::Portlet-->
            <div class="kt-portlet">
                <div class="kt-portlet__head">
                    <div class="kt-portlet__head-label">
                        <h3 class="kt-portlet__head-title">
                            Информация за контакта
                        </h3>
                    </div>
                </div>

                <!--begin::Form-->
                <form class="kt-form" method="POST" action="{{ route('contacts.update', $contact->id) }}">
                    @csrf
                    @method('PUT')

                    <div class="kt-portlet__body">
                        @if($errors->any())
                            <div class="form-group form-group-last">
                                <div class="alert alert-danger" role="alert">
                                    <div class="alert-icon"><i class="flaticon-warning kt-font-white"></i></div>
                                    <div class="alert-text">
                                        Възникнаха грешки
                                    </div>
                                </div>
                            </div>
                        @endif
                        <div class="form-group">
                            <label for="first_name">Име</label>
                            <input type="text" class="form-control" name="first_name" id="first_name" value="{{ old('first_name') ?? $contact->first_name }}">
                            @error('first_name') <span class="form-text text-danger">{{ $message }}</span> @enderror
                        </div>
                        <div class="form-group">
                            <label for="last_name">Фамилия</label>
                            <input type="text" class="form-control" name="last_name" id="last_name" value="{{ old('last_name') ?? $contact->last_name }}">
                            @error('last_name') <span class="form-text text-danger">{{ $message }}</span> @enderror
                        </div>
                        <div class="form-group">
                            <label for="email">Имейл адрес</label>
                            <input type="email" class="form-control" name="email" id="email" value="{{ old('email') ?? $contact->email }}">
                            @error('email') <span class="form-text text-danger">{{ $message }}</span> @enderror
                        </div>
                    </div>
                    <div class="kt-portlet__foot">
                        <div class="kt-form__actions text-right">
                            <button type="submit" class="btn btn-primary">Редактирай</button>
                        </div>
                    </div>
                </form>

                <!--end::Form-->
            </div>

            <!--end::Portlet-->

        </div>
    </div>
@endsection

resources/views/contacts/index.blade.php
@extends('layouts.master')

@section('title', 'Contacts')
@section('page-title', 'Contacts')

@section('content')
<!-- begin:: Content -->
<div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
    <div class="kt-portlet kt-portlet--mobile">
        <div class="kt-portlet__head kt-portlet__head--lg">
            <div class="kt-portlet__head-label">
                <span class="kt-portlet__head-icon">
                    <i class="kt-font-brand flaticon-user"></i>
                </span>
                <h3 class="kt-portlet__head-title">
                    Contacts
                </h3>
            </div>
            <div class="kt-portlet__head-toolbar">
                <div class="kt-portlet__head-wrapper">
                    <div class="kt-portlet__head-actions">
                        <a href="{{ route('contacts.create') }}" class="btn btn-brand btn-elevate btn-icon-sm">
                            <i class="la la-plus"></i>
                            New Contact
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="kt-portlet__body">
            <div class="dropzone dropzone-default p-0" id="kt_dropzone_1">
                <div class="dropzone-msg dz-message needsclick">
                    <h3 class="dropzone-msg-title">Пуснете CSV файл тук или кликнете за да качите.</h3>
                    <span class="dropzone-msg-desc">Структурата е: {first_name},{last_name},{email}</span>
                </div>
            </div>
            <div class="kt-portlet__body">


                <!--begin: Search Form -->
                <div class="kt-form kt-form--label-right kt-margin-t-20 kt-margin-b-10">
                    <div class="row align-items-center">
                        <div class="col-xl-8 order-2 order-xl-1">
                            <div class="row align-items-center">
                                <div class="col-md-4 kt-margin-b-20-tablet-and-mobile">
                                    <div class="kt-input-icon kt-input-icon--left">
                                        <input type="text" class="form-control" placeholder="Търси..." id="generalSearch">
                                        <span class="kt-input-icon__icon kt-input-icon__icon--left">
                                            <span><i class="la la-search"></i></span>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!--end: Search Form -->

                @component('components.contacts.contacts-controls', ['options' => ['delete', 'group'], 'groups' => $groups])
                @endcomponent
            </div>
            <div class="kt-portlet__body kt-portlet__body--fit">

                @component('components.contacts.contacts-datatable', ['id' => 'contacts-table', 'contacts' => $contacts])
                @endcomponent
            </div>
        </div>
    </div>

    <!-- end:: Content -->
    @endsection

    @push('scripts')
    <script type="text/javascript">
        $(document).ready(function() {
            $('.select2').select2();

            // single file upload
            $('#kt_dropzone_1').dropzone({
                url: "{{ route('contacts.import') }}", // Set the url for your upload script location
                headers: {
                    "X-CSRF-TOKEN": "{{ csrf_token() }}"
                },
                paramName: "file", // The name that will be used to transfer the file
                maxFiles: 1,
                maxFilesize: 5, // MB
                addRemoveLinks: true
            });
        });
    </script>
    @endpush