routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Contacts
Route::delete('/contacts/delete-multiple', 'ContactController@destroyMultiple')->name('contacts.delete-multiple');
Route::post('/contacts/import', 'ContactController@import')->name('contacts.import');
Route::resource('contacts', 'ContactController');


//Groups
Route::delete('/groups/delete-multiple', 'GroupController@destroyMultiple')->name('groups.delete-multiple');
Route::post('/groups/add-contacts', 'GroupController@addContacts')->name('groups.add-contacts');
Route::resource('groups', 'GroupController');
Route::get('/groups/{group}/contacts', 'GroupController@getContacts')->name('groups.get-contacts');

// Campaigns
Route::resource('campaigns', 'CampaignController');

//mails
Route::get('email', 'CampaignController@store');

Route::resource('support', 'SupportController');

app/Group.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Group extends Model
{
    /**
     * Create a new Eloquent Collection instance.
     *
     * @param  array  $models
     * @return \Illuminate\Database\Eloquent\Collection
     */
    // public function newCollection(array $models = [])
    // {
    //     return new GroupCollection($models);
    // }

    // Relations
    public function user()
    {
        return $this->belongsTo('App\User')->withDefault([
            'name' => '-'
        ]);
    }

    public function contacts()
    {
        return $this->belongsToMany('App\Contact');
    }
}

app/Http/Controllers/GroupController.php
<?php

namespace App\Http\Controllers;

use App\Contact;
use App\Group;
use App\Http\Requests\Groups\AddContactsRequest;
use App\Http\Requests\Groups\StoreGroupRequest;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;

class GroupController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $groups = Auth::user()->groups;
        
        return view('groups.index', compact("groups"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $contacts = Auth::user()->contacts;

        return view('groups.create', compact("contacts"));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\Groups\StoreGroupRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $group = new Group;
        $group->user()->associate(Auth::user());
        $group->name = $request->name;
        $group->save();

        $group->contacts()->attach($request->contacts);

        return redirect()->route('groups.index')->with('success', 'The group was created');
    }

    public function addContacts(Request $request)
    {
        $group = Group::find($request->group);

        $group->contacts()->attach($request->contacts);

        return redirect()->route('groups.index')->with('success', 'The contacts were added');
    }


    /**
     * Display the specified resource.
     *
     * @param  \App\Group  $group
     * @return \Illuminate\Http\Response
     */
    public function show(Group $group)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Group  $group
     * @return \Illuminate\Http\Response
     */
    public function edit(Group $group)
    {
        $contacts = Auth::user()->contacts;

        return view('groups.edit', compact("group", "contacts"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Group  $group
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Group $group)
    {
        $group->name = $request->name;
        $group->save();

        $group->contacts()->sync($request->contacts);

        return redirect()->route('groups.index')->with('success', 'The group was updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Group  $group
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, Group $group)
    {
        if ($group->delete()) {
            if ($request->ajax()) {
                return response()->json([
                    'success' => true,
                    'message' => 'The group was deleted'
                ]);
            }

            return redirect()->back()->with('success', 'The group was deleted');
        }

        if ($request->ajax()) {
            return response()->json([
                'success' => false,
                'message' => 'There was a problem deleting the group'
            ]);
        }

        return redirect()->back()->with('error', 'There was a problem deleting the group');
    }

    /**
     * Remove multiple specified resources from storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function destroyMultiple(Request $request)
    {
        $groups = Group::whereIn('id', $request->groups)->get();

        if (Group::whereIn('id', $request->groups)->delete()) {
            if ($request->ajax()) {
                return response()->json([
                    'success' => true,
                    'message' => 'The Groups were deleted'
                ]);
            }

            return redirect()->back()->with('success', 'The Groups were deleted');
        }

        if ($request->ajax()) {
            return response()->json([
                'success' => false,
                'message' => 'There was a problem with deleting groups'
            ]);
        }

        return redirect()->back()->with('error', 'There was a problem with deleting groups');
    }

    public function getContacts(Group $group)
    {
        return response()->json($group->contacts);
    }
}

app/Http/Controllers/Groups/AddContactsRequest.php
<?php

namespace App\Http\Requests\Groups;

use Auth;
use Illuminate\Foundation\Http\FormRequest;

class composer require maatwebsite/excelAddContactsRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'group' => 'required|integer|exists:groups,id,user_id,'.Auth::user()->id,
            'contacts' => 'required|array',
            'contacts.*' => 'integer|exists:contacts,id,user_id,'.Auth::user()->id
        ];
    }
}

app/Http/Controllers/Groups/StoreGroupRequest.php
<?php

namespace App\Http\Requests\Groups;

use Auth;
use Illuminate\Foundation\Http\FormRequest;

class StoreGroupRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name' => 'required|string|max:250',
            'contacts' => 'nullable|array',
            'contacts.*' => 'integer|exists:contacts,id,user_id,'.Auth::user()->id
        ];
    }
}

resources/views/groups/create.blade.php
@extends('layouts.master')

@section('title', 'Създай група')
@section('page-title', 'Създай група')

@section('content')
    <div class="row">
        <div class="col-md-8">

            <!--begin::Portlet-->
            <div class="kt-portlet">
                <div class="kt-portlet__head">
                    <div class="kt-portlet__head-label">
                        <h3 class="kt-portlet__head-title">
                            Информация за групата
                        </h3>
                    </div>
                </div>

                <!--begin::Form-->
                <form class="kt-form" method="POST" action="{{ route('groups.store') }}">
                    @csrf

                    <div class="kt-portlet__body">
                        @if($errors->any())
                            <div class="form-group form-group-last">
                                <div class="alert alert-danger" role="alert">
                                    <div class="alert-icon"><i class="flaticon-warning kt-font-white"></i></div>
                                    <div class="alert-text">
                                        Възникнаха грешки
                                    </div>
                                </div>
                            </div>
                        @endif
                        <div class="form-group">
                            <label for="name">Име</label>
                            <input type="text" class="form-control" name="name" id="name" value="{{ old('name') }}">
                            @error('name') <span class="form-text text-danger">{{ $message }}</span> @enderror
                        </div>
                        <div class="form-group">
                            <div id="contacts_list">

                            </div>
                            <label for="contacts">Контакти</label>
                            <select class="kt-dual-listbox" id="contacts" name="contacts[]" multiple>
                                @foreach($contacts as $contact)
                                    <option value="{{ $contact->id }}"{{ in_array($contact->id, old('contacts') ?? []) ? ' selected' : '' }}>{{ $contact->fullName() }}</option>
                                @endforeach
                            </select>
                            @error('contacts') <span class="form-text text-danger">{{ $message }}</span> @enderror
                        </div>
                    </div>
                    <div class="kt-portlet__foot">
                        <div class="kt-form__actions text-right">
                            <button type="submit" class="btn btn-primary">Създай</button>
                        </div>
                    </div>
                </form>

                <!--end::Form-->
            </div>

            <!--end::Portlet-->

        </div>
    </div>
@endsection

@push('scripts')
    <script src="{{ asset('assets/js/pages/components/extended/dual-listbox.js') }}"></script>
@endpush

resources/views/groups/edit.blade.php
@extends('layouts.master')

@section('title', 'Редактирай група')
@section('page-title', 'Редактирай група')

@section('content')
    <div class="row">
        <div class="col-md-8">

            <!--begin::Portlet-->
            <div class="kt-portlet">
                <div class="kt-portlet__head">
                    <div class="kt-portlet__head-label">
                        <h3 class="kt-portlet__head-title">
                            Информация за групата
                        </h3>
                    </div>
                </div>

                <!--begin::Form-->
                <form class="kt-form" method="POST" action="{{ route('groups.update', $group->id) }}">
                    @csrf
                    @method('PUT')

                    <div class="kt-portlet__body">
                        @if($errors->any())
                            <div class="form-group form-group-last">
                                <div class="alert alert-danger" role="alert">
                                    <div class="alert-icon"><i class="flaticon-warning kt-font-white"></i></div>
                                    <div class="alert-text">
                                        Възникнаха грешки
                                    </div>
                                </div>
                            </div>
                        @endif
                        <div class="form-group">
                            <label for="name">Име</label>
                            <input type="text" class="form-control" name="name" id="name" value="{{ old('name') ?? $group->name }}">
                            @error('name') <span class="form-text text-danger">{{ $message }}</span> @enderror
                        </div>
                        <div class="form-group">
                            <div id="contacts_list">

                            </div>
                            <label>Контакти</label>
                            <select class="kt-dual-listbox" multiple>
                                @foreach($contacts as $contact)
                                    <option value="{{ $contact->id }}"{{ in_array($contact->id, old('contacts') ? old('contacts') : $group->contacts->pluck('id')->toArray()) ? ' selected' : '' }}>{{ $contact->fullName() }}</option>
                                @endforeach
                            </select>
                            @error('contacts') <span class="form-text text-danger">{{ $message }}</span> @enderror
                        </div>
                    </div>
                    <div class="kt-portlet__foot">
                        <div class="kt-form__actions text-right">
                            <button type="submit" class="btn btn-primary">Редактирай</button>
                        </div>
                    </div>
                </form>

                <!--end::Form-->
            </div>

            <!--end::Portlet-->

        </div>
    </div>
@endsection

@push('scripts')
    <script src="{{ asset('assets/js/pages/components/extended/dual-listbox.js') }}"></script>
@endpush

resources/views/groups/index.blade.php
@extends('layouts.master')

@section('title', 'Групи')
@section('page-title', 'Групи')

@section('content')
    <!-- begin:: Content -->
    <div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
        <div class="kt-portlet kt-portlet--mobile">
            <div class="kt-portlet__head kt-portlet__head--lg">
                <div class="kt-portlet__head-label">
										<span class="kt-portlet__head-icon">
											<i class="kt-font-brand flaticon2-group"></i>
										</span>
                    <h3 class="kt-portlet__head-title">
                        Групи
                    </h3>
                </div>
                <div class="kt-portlet__head-toolbar">
                    <div class="kt-portlet__head-wrapper">
                        <div class="kt-portlet__head-actions">
                            <a href="{{ route('groups.create') }}" class="btn btn-brand btn-elevate btn-icon-sm">
                                <i class="la la-plus"></i>
                                Нова група
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="kt-portlet__body">

                <!--begin: Search Form -->
                <div class="kt-form kt-form--label-right kt-margin-t-20 kt-margin-b-10">
                    <div class="row align-items-center">
                        <div class="col-xl-8 order-2 order-xl-1">
                            <div class="row align-items-center">
                                <div class="col-md-4 kt-margin-b-20-tablet-and-mobile">
                                    <div class="kt-input-icon kt-input-icon--left">
                                        <input type="text" class="form-control" placeholder="Търси..." id="generalSearch">
                                        <span class="kt-input-icon__icon kt-input-icon__icon--left">
																<span><i class="la la-search"></i></span>
															</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!--end: Search Form -->

                @component('components.groups.groups-controls', ['options' => ['delete']])
                @endcomponent
            </div>
            <div class="kt-portlet__body kt-portlet__body--fit">

                @component('components.groups.groups-datatable', ['id' => 'groups-table', 'groups' => $groups])
                @endcomponent
            </div>
        </div>
    </div>

    <!-- end:: Content -->
@endsection