routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Contacts
Route::delete('/contacts/delete-multiple', 'ContactController@destroyMultiple')->name('contacts.delete-multiple');
Route::post('/contacts/import', 'ContactController@import')->name('contacts.import');
Route::resource('contacts', 'ContactController');


//Groups
Route::delete('/groups/delete-multiple', 'GroupController@destroyMultiple')->name('groups.delete-multiple');
Route::post('/groups/add-contacts', 'GroupController@addContacts')->name('groups.add-contacts');
Route::resource('groups', 'GroupController');
Route::get('/groups/{group}/contacts', 'GroupController@getContacts')->name('groups.get-contacts');

// Campaigns
Route::resource('campaigns', 'CampaignController');

//mails
Route::get('email', 'CampaignController@store');

Route::resource('support', 'SupportController');

app/Campaign.php
<?php

namespace App;


use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Campaign extends Model
{
     // Relations
     public function user()
     {
         return $this->belongsTo('App\User');
     }
 
     public function status()
     {
         return $this->belongsTo('App\CampaignStatus');
     }
 
     public function template()
     {
         return $this->belongsTo('App\CampaignTemplate');
     }
 
     public function contacts()
     {
         return $this->belongsToMany('App\Contact');
     }
 
     // Helper functions
     public function deleteLogo()
     {
         if (Storage::disk('local')->exists('logos/'.$this->image)) {
             Storage::disk('local')->delete('logos/'.$this->image);
         }
 
         return true;
     }
}

app/Http/Controllers/CampaignController.php
<?php

namespace App\Http\Controllers;

use App\Campaign;
use App\CampaignStatus;
use App\CampaignTemplate;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Storage;
use App\Mail\NewMail;

    class CampaignController extends Controller
{
    //Hasing function for the image name
    private function hashImageName($image)
    {
        return md5($image->getClientOriginalName() . uniqid('weband')) . '.' . $image->getClientOriginalExtension();
    }

    /**
     * CampaignController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth');
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $campaigns = Auth::user()->campaigns;
        $statuses = CampaignStatus::all();

        return view('campaigns.index', compact("campaigns", "statuses"));
    }

    public function getCampaigns()
    {

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $templates = CampaignTemplate::all();
        $contacts = Auth::user()->contacts;
        $groups = Auth::user()->groups;

        return view('campaigns.create', compact("templates", "groups", "contacts"));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $campaign = new Campaign;
        $campaign->user()->associate(Auth::user());
        $campaign->name = $request->name;
        $campaign->from = $request->from;
        $campaign->subject = $request->subject;
        $campaign->template()->associate($request->template);
        $campaign->title = $request->title;
        $campaign->text = $request->text;
        $campaign->button_text = $request->button_text;
        $campaign->button_color = $request->button_color;
        //Check if image is presented in the request and it's valid
        if($request->hasFile('logo') && $request->logo->isValid()) {
            $logo = $request->logo;
            $image_name = $this->hashImageName($logo);
            //store the image in the filesystem
            Storage::disk('local')->putFileAs('logos', $logo, $image_name);
            //store the path as text in the database
            $campaign->logo = $image_name;
        }

        $campaign->save();
        $campaign->contacts()->attach($request->contacts);
        
        Mail::to('example@example.com')->send(new NewMail($request));
        if ($request->ajax()) {
            return response()->json(['success' => true, 'message' => 'Campany was added.', 'redirect' => route('campaigns.index')]);
        }

        return redirect()->route('campaigns.index')->with('success', 'Campany was added.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Campaign  $campaign
     * @return \Illuminate\Http\Response
     */
    public function show(Campaign $campaign)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Campaign  $campaign
     * @return \Illuminate\Http\Response
     */
    public function edit(Campaign $campaign)
    {
        $this->authorize('update', $campaign);

        $templates = CampaignTemplate::all();
        $contacts = Auth::user()->contacts;
        $groups = Auth::user()->groups;

        return view('campaigns.edit', compact("campaign", "templates", "contacts", "groups"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Campaign  $campaign
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Campaign $campaign)
    {
        $this->authorize('update', $campaign);

        $campaign->name = $request->name;
        $campaign->from = $request->from;
        $campaign->subject = $request->subject;
        $campaign->template()->associate($request->template);
        $campaign->title = $request->title;
        $campaign->text = $request->text;
        $campaign->button_text = $request->button_text;
        $campaign->button_color = $request->button_color;

        //Check if image is presented in the request and it's valid
        if($request->hasFile('logo') && $request->logo->isValid()) {
            $logo = $request->logo;
            $image_name = $this->hashImageName($logo);

            //store the image in the filesystem
            Storage::disk('local')->putFileAs('logos', $logo, $image_name);

            $campaign->deleteLogo();

            //store the path as text in the database
            $campaign->logo = $image_name;
        }

        $campaign->save();

        $campaign->contacts()->sync($request->contacts);

        if ($request->ajax()) {
            return response()->json(['success' => true, 'message' => 'Campany was edited.', 'redirect' => route('campaigns.index')]);
        }

        return redirect()->route('campaigns.index')->with('success', 'Campany was added.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Campaign  $campaign
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, Campaign $campaign)
    {
        $this->authorize('delete', $campaign);

        $campaign->deleteLogo();
        $campaign->delete();

        if ($request->ajax()) {
            return response()->json(['success' => true, 'message' => 'Campany was deleted']);
        }

        return redirect()->back()->with('success', 'Campany was deleted');
    }
}

resources/views/campaigns/index.blade.php
@extends('layouts.master')

@section('title', 'Кампании')
@section('page-title', 'Кампании')

@section('content')
    <!-- begin:: Content -->
    <div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
        <div class="kt-portlet kt-portlet--mobile">
            <div class="kt-portlet__head kt-portlet__head--lg">
                <div class="kt-portlet__head-label">
                    <span class="kt-portlet__head-icon">
                        <i class="kt-font-brand flaticon2-mail-1"></i>
                    </span>
                    <h3 class="kt-portlet__head-title">
                        Кампании
                    </h3>
                </div>
                <div class="kt-portlet__head-toolbar">
                    <div class="kt-portlet__head-wrapper">
                        <div class="kt-portlet__head-actions">
                            <a href="{{ route('campaigns.create') }}" class="btn btn-brand btn-elevate btn-icon-sm">
                                <i class="la la-plus"></i>
                                Нова кампания
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="kt-portlet__body">
                <!--begin: Search Form -->
                <div class="kt-form kt-form--label-right kt-margin-t-20 kt-margin-b-10">
                    <div class="row align-items-center">
                        <div class="col-xl-8 order-2 order-xl-1">
                            <div class="row align-items-center">
                                <div class="col-md-4 kt-margin-b-20-tablet-and-mobile">
                                    <div class="kt-input-icon kt-input-icon--left">
                                        <input type="text" class="form-control" placeholder="Търси..." id="generalSearch">
                                        <span class="kt-input-icon__icon kt-input-icon__icon--left">
																<span><i class="la la-search"></i></span>
															</span>
                                    </div>
                                </div>
                               {{-- <div class="col-md-4 kt-margin-b-20-tablet-and-mobile">
                                    <div class="kt-form__group kt-form__group--inline">
                                        <div class="kt-form__label">
                                            <label>Статус:</label>
                                        </div>
                                        <div class="kt-form__control">
                                            <select class="form-control bootstrap-select" id="kt_form_status">
                                                <option value="">Всички</option>
                                                @foreach($statuses as $status)
                                                    <option value="{{ $status->id }}">{{ $status->name }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                </div>--}}
                            </div>
                        </div>
                    </div>
                </div>

                <!--end: Search Form -->

                {{--@component('components.contacts.contacts-controls', ['options' => ['delete']])
                @endcomponent--}}
            </div>
            <div class="kt-portlet__body kt-portlet__body--fit">
                <table class="kt-datatable" id="campaigns-table" width="100%">
                    <thead>
                        <tr>
                            <th>Име</th>
                            <th>От</th>
                            <th>Относно</th>
                            <th>Действия</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($campaigns as $campaign)
                            <tr id="campaign-{{ $campaign->id }}">
                                <td>{{ $campaign->name }}</td>
                                <td>{{ $campaign->from }}</td>
                                <td>{{ $campaign->subject }}</td>
                                <td>
                                    <div class="dropdown">
                                        <a href="javascript:;" class="btn btn-sm btn-clean btn-icon btn-icon-md" data-toggle="dropdown">
                                            <i class="flaticon-more-1"></i>
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-right">
                                            <ul class="kt-nav">
                                                <li class="kt-nav__item">
                                                    <a href="{{ route('campaigns.edit', $campaign->id) }}" class="kt-nav__link">
                                                        <i class="kt-nav__link-icon la la-edit"></i>
                                                        <span class="kt-nav__link-text">Редактирай</span>
                                                    </a>
                                                </li>
                                                <li class="kt-nav__item">
                                                    <a href="#" class="kt-nav__link delete-resource" data-delete-route="{{ route('campaigns.destroy', $campaign->id) }}" data-row-id="campaign-{{ $campaign->id }}">
                                                        <i class="kt-nav__link-icon la la-trash"></i>
                                                        <span class="kt-nav__link-text">Изтрий</span>
                                                    </a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <!-- end:: Content -->
@endsection

@push('scripts')
    @component('components.sweet-alert.delete')
    @endcomponent

    <script type="text/javascript">
        $(document).ready(function() {

            // single file upload
            var datatable = $('#campaigns-table').KTDatatable({
                rows: {
                    autoHide: false
                },
                search: {
                    input: $('#generalSearch')
                },
                columns: [
                    {
                        field: 'ID',
                        title: '#',
                        sortable: false,
                        width: 20,
                        type: 'number',
                        selector: {class: 'kt-checkbox--solid'},
                        textAlign: 'center'
                    },
                    /*{
                        field: 'Status',
                        title: 'Статус',
                        // callback function support for column rendering
                        template: function(row) {
                            var status = {
                                1: {'title': 'Изпратена', 'class': ' kt-badge--success'},
                                2: {'title': 'Draft', 'class': 'kt-badge--warning'},
                                3: {'title': 'Scheduled', 'class': ' kt-badge--brand'},
                            };
                            return '<span class="kt-badge ' + status[row.Status].class + ' kt-badge--inline kt-badge--pill">' + status[row.Status].title + '</span>';
                        },
                    },*/
                    {
                        field: 'Действия',
                        sortable: false
                    }
                ]
            });

            $('#kt_form_status').on('change', function() {
                datatable.search($(this).val().toLowerCase(), 'Статус');
            });

            $('#kt_form_status').selectpicker();
        });
    </script>
@endpush